- name: Setting up
  # hosts: ninja
  hosts: all
  gather_facts: yes
  tasks:
    - name: Add User
      win_user:
        name: testuser
        password: "testuser"
        state: present

    - name: set timezone to Asia/Kolkata
      timezone:
        name: Asia/Kolkata

    # - name: example copying file with owner and permissions
    #   copy:
    #     src: foo.conf
    #     dest: /etc/foo.conf
    #     owner: testuser
    #     group: testuser
    #     mode: 0644

        # Install Python 3.3
    - name: Download Python 3.3
      get_url: dest=/var/local/ansible-cache url=http://www.python.org/ftp/python/3.3.5/Python-3.3.5.tar.xz 
      sudo: yes

    - name: Ensure Python 3.3 is extracted
      shell: chdir=/var/local/ansible-cache tar xJf ./Python-3.3.5.tar.xz -C /opt creates=/opt/Python-3.3.5
      sudo: yes

    - name: Ensure Python 3.3 is configured
      shell: chdir=/opt/Python-3.3.5 ./configure --prefix=/opt/python3.3

    - name: Ensure Python 3.3 make'd
      shell: chdir=/opt/Python-3.3.5 make

    - name: Ensure Python 3.3 installed
      shell: chdir=/opt/Python-3.3.5 make install  # Need to add a 'creates=' flag here
      sudo: yes

    # - name: Install packages required
    #   pip: name={{ item }}
    #   with_items: 
    #     - supervisor

    - name: Install Supervisor
      apt: name=supervisor state=latest