- name: Setting up
  # hosts: ninja
  hosts: ninja
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  tasks:

    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present

    - name: Safe system upgrade via aptitude
      apt: upgrade=safe

    - name: install python-apt for debian
      action: command /usr/bin/apt-get install -y python-apt

    - name: install git
      apt: 
        name: git
        state: present
        update-cache: yes

    - name: set timezone to Asia/Kolkata
      timezone:
        name: Asia/Kolkata

    - remote_user: vagrant
      become: true
      become_method: sudo
      become_user: root
      user:
        name: testuser
        groups: admin
        append: yes
        shell: /bin/bash
        password: testuser
        state: present

    - name: Install Supervisor
      apt: name=supervisor state=latest

    # - name: Install consul
    #   shell: 
