- name: Setting up
  # hosts: ninja
  hosts: ninja
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  tasks:

    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present

    - name: Safe system upgrade via aptitude
      apt: upgrade=safe

    - name: install python-apt for debian
      apt: pkg="{{item}}" state=present update-cache=yes
      with_items:
       - python-apt
       - unzip
       - supervisor

    - name: set timezone to Asia/Kolkata
      timezone:
        name: Asia/Kolkata

    - remote_user: vagrant
      become: true
      become_method: sudo
      become_user: root
      user:
        name: testuser
        groups: admin
        append: yes
        shell: /bin/bash
        password: testuser
        state: present

    - name: Install consul
      get_url: url={{  "https://releases.hashicorp.com/consul/1.1.0/consul_1.1.0_linux_amd64.zip" }} dest={{ "/home/vagrant/"}}/{{ "consul_1.1.0_linux_amd64.zip" }}

    - name: unzip
      shell: "unzip /home/vagrant/consul_1.1.0_linux_amd64.zip -d /usr/bin/"